version: "3"
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    volumes:
      - mysql_volume:/app/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cafe
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    networks:
      - docker-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  spring-container:
    container_name: spring-container
    ports:
      - "8080:8080"
    image: njm1250/payhere_backend
    volumes:
      - njm1250_images:/app/njm1250/images
    networks:
      - docker-network
    depends_on:
      mysql-container:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-container:3306/cafe
networks:
  docker-network:
    driver: bridge
volumes:
  mysql_volume:
    driver: local
  njm1250_images:
    driver: local